url: https://mustilica.github.io
baseurl: /notebook-project
dropboxbaseurl: https://dl.dropboxusercontent.com/u/8737486/staticProjects/notebook-project

title: Notebook Project
email: notebook.project@kulu.be
description: "trash, junk, garbage, rubbish, notebook, craft, art, art project, transformation, treasure"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary:  00bcd4
  secondary: 00acc1
  secondary-dark: 333

# Social networks
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: instagram
    url: http://stackoverflow.com/questions/tagged/jekyll

# Build settings
markdown: kramdown
permalink: pretty

collections:
  notebooks:
    output: true
  trashes:
    output: true
  modals:

exclude: [README.md, LICENSE]
